### ISSUE TITLE
Cannot download files

### ISSUE THREAD

**Issue by suotroel** [srevinsaju/Firefox-Appimage#23]
Since a couple or three versions ago I'm not able to download any files with FF-stable or FF-esr appimages.

I have no problem with LibreWolf appimage (another appimage derivative of FF-stable).

I'm running Debian-stable with Xfce.

**Comment by suotroel** [comment]
It seems nobody cares. Mmmm....

**Comment by srevinsaju** [comment]
Weird, is probably out of the scope for this repository. You might want to raise a support ticket with GitHub instead

**Comment by suotroel** [comment]
These FF-appimages are unable to save files or to open a bookmark's backup file. It seems that they are unable to reach a directory, unable to interact with the file system. It doesn't happen with regular FF o with LibreFox.

**Comment by srevinsaju** [comment]
Sorry I cannot reproduce this issue any more, can you please try the latest versions of firefox AppImages to see if this issue still exists?

**Comment by IdolIcon** [comment]
Can't you reproduce this issue? Why? None of you have a computer?

Well, don't worry, I've got one. And you know what? Surprise!! Your Firefox-ESR appimages are unable to download anything. Who could imagine it?

But I'm sure that in a couple or three months someone with no manners will come, he won't be polite, he won't be cool, he will be insulted, but in the end you will address the problem. It's just a matter of time...

**Comment by srevinsaju** [comment]
Since you are able to reproduce the issue, can you run the AppImage from the terminal to see if Firefox is generating any errors? If yes, I can investigate on them

**Comment by IdolIcon** [comment]
Done. There are no error messages.

It seems that the FF-esr appimage is unable to reach the file system. It's unable to download anything, but is unable to open anything from the file system as well: You select "open" and absolutely nothing happens.

**Comment by srevinsaju** [comment]
Thanks for testing, may I know which desktop environment you are using? Not sure if it is related. Also, do you have something like `firejail` installed?

To check if its related to some existing config, I tried this:
```
./firefox-esr.....AppImage --appimage-portable-home
./firefox-esr.....AppImage --appimage-portable-config 
./firefox-esr.....AppImage # which now uses the portable config folder and home 
```
but still the download works, the Downloads are now stored in ~/firefox-esr..../Downloads. Let me know if this approach works, if yes, we can narrow down the scope of the problem.

**Comment by srevinsaju** [comment]
By a regular installation, do you mean, those which are installed from the package manager for your distribution? Can you also test using the binary provided by firefox here: https://www.mozilla.org/en-US/firefox/all/#product-desktop-esr to see if the issue does not exist with this one?

I am wondering if the issue is related to the rewrite of many firefox features (esr-next to esr), which possibly broke some config.

**Comment by IdolIcon** [comment]
Done.

Debian's default FF is the ESR version. I installed it, it worked properly when clean and with my complete configuration.

As you suggested, I downloaded the binary provided by Mozilla of FF-ESR as well. It worked properly clean and with my complete configuration.

**Comment by srevinsaju** [comment]
Ok, but the issue on latest Firefox ESR 102.5 AppImage still exists? Also do you use any appimage utilities like [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher)

**Comment by IdolIcon** [comment]
Yes, your last ESR appimage can't open or save anything with my configuration (it can do it when it is clean). But Mozilla's FF-ESR binary works properly with my configuration.

To open appimages I just use a launcher from my desktop panel (on the other hand, double click on the FF-esr appimage doesn't change its weird behaviour).

**Comment by marc1uk** [comment]
Hi. I've tried with the latest version of the appimage (v111), with my current and a fresh profile, as well as starting firefox in safe mode (all extensions disabled etc). The issue persists.
When running from the terminal the following warning appeared when I tried to use File->Open:

```
(firefox:22209): Gtk-WARNING **: Can't open portal file chooser: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
```

**Comment by marc1uk** [comment]
googled that error,  seems it's a common thing with flatpaks/snaps/appimages. various suggestions: 
* installed `xdg-desktop-portal` and `xdg-desktop-portal-gtk`
neither of these alone or both fixed it, so not sure if they're needed. But what did fix it was:
* set `widget.use-xdg-desktop-portal.file-picker` to `0` in the `about:config` in Firefox.

File dialogs now work as expected! Hurrah! :tada:
